OutLocation=C:\Users\primary\Desktop\logparse
HtmlExternalScriptsCdn=
CompressRaw=False
UploadToWingman=False
SkipFailedTries=False
IndentJSON=False
WebhookURL=
ParseMultipleLogs=True
UploadToRaidar=False
HtmlCompressJson=False
HtmlExternalScriptsPath=
ParsePhases=True
AutoDiscordBatch=False
PopulateHourLimit=0
SaveOutXML=False
ComputeDamageModifiers=True
AddPoVProf=False
Outdated=False
HtmlExternalScripts=False
SaveAtOut=True
SaveOutHTML=True
ApplicationTraces=False
MemoryLimit=0
Anonymous=False
SendEmbedToWebhook=False
IndentXML=False
SingleThreaded=False
UploadToDPSReports=False
DetailledWvW=True
CustomTooShort=2200
ParseCombatReplay=True
DPSReportUserToken=
SaveOutJSON=True
SendSimpleMessageToWebhook=False
AutoParse=False
RawTimelineArrays=True
AutoAdd=False
AddDuration=False
SaveOutTrace=True
AutoAddPath=
SaveOutCSV=False
LightTheme=False
